// This file is generated by a T4 template. Do not edit manually.

// Note:
// Some types can be directly stored in "ApplicationData.Current.LocalSettings": 
// https://docs.microsoft.com/windows/apps/design/app-settings/store-and-retrieve-app-data#settings
// Unfortunately there's no way to constraint a generic type "T" to "T1 or T2" in C#, so I have to use a T4 template to generate these methods.

using Windows.Foundation.Collections;
using Windows.Storage;

namespace EnergyStarX.Helpers;

public static class LocalSettingsHelper
{
    private static IPropertySet LocalSettings => ApplicationData.Current.LocalSettings.Values;

    public static int ReadPrimitive(string key, int defaultValue)
    {
        if (LocalSettings.TryGetValue(key, out object? obj))
        {
            if (obj is int value)
            {
                return value;
            }
        }
        return defaultValue;
    }

    public static void SetPrimitive(string key, int value)
    {
        LocalSettings[key] = value;
    }

    public static long ReadPrimitive(string key, long defaultValue)
    {
        if (LocalSettings.TryGetValue(key, out object? obj))
        {
            if (obj is long value)
            {
                return value;
            }
        }
        return defaultValue;
    }

    public static void SetPrimitive(string key, long value)
    {
        LocalSettings[key] = value;
    }

    public static float ReadPrimitive(string key, float defaultValue)
    {
        if (LocalSettings.TryGetValue(key, out object? obj))
        {
            if (obj is float value)
            {
                return value;
            }
        }
        return defaultValue;
    }

    public static void SetPrimitive(string key, float value)
    {
        LocalSettings[key] = value;
    }

    public static double ReadPrimitive(string key, double defaultValue)
    {
        if (LocalSettings.TryGetValue(key, out object? obj))
        {
            if (obj is double value)
            {
                return value;
            }
        }
        return defaultValue;
    }

    public static void SetPrimitive(string key, double value)
    {
        LocalSettings[key] = value;
    }

    public static bool ReadPrimitive(string key, bool defaultValue)
    {
        if (LocalSettings.TryGetValue(key, out object? obj))
        {
            if (obj is bool value)
            {
                return value;
            }
        }
        return defaultValue;
    }

    public static void SetPrimitive(string key, bool value)
    {
        LocalSettings[key] = value;
    }

    public static char ReadPrimitive(string key, char defaultValue)
    {
        if (LocalSettings.TryGetValue(key, out object? obj))
        {
            if (obj is char value)
            {
                return value;
            }
        }
        return defaultValue;
    }

    public static void SetPrimitive(string key, char value)
    {
        LocalSettings[key] = value;
    }

    public static string ReadPrimitive(string key, string defaultValue)
    {
        if (LocalSettings.TryGetValue(key, out object? obj))
        {
            if (obj is string value)
            {
                return value;
            }
        }
        return defaultValue;
    }

    public static void SetPrimitive(string key, string value)
    {
        LocalSettings[key] = value;
    }

    public static DateTime ReadPrimitive(string key, DateTime defaultValue)
    {
        if (LocalSettings.TryGetValue(key, out object? obj))
        {
            if (obj is DateTime value)
            {
                return value;
            }
        }
        return defaultValue;
    }

    public static void SetPrimitive(string key, DateTime value)
    {
        LocalSettings[key] = value;
    }

    public static TimeSpan ReadPrimitive(string key, TimeSpan defaultValue)
    {
        if (LocalSettings.TryGetValue(key, out object? obj))
        {
            if (obj is TimeSpan value)
            {
                return value;
            }
        }
        return defaultValue;
    }

    public static void SetPrimitive(string key, TimeSpan value)
    {
        LocalSettings[key] = value;
    }

    public static Guid ReadPrimitive(string key, Guid defaultValue)
    {
        if (LocalSettings.TryGetValue(key, out object? obj))
        {
            if (obj is Guid value)
            {
                return value;
            }
        }
        return defaultValue;
    }

    public static void SetPrimitive(string key, Guid value)
    {
        LocalSettings[key] = value;
    }

}